export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  typeformApiToken: process.env.TYPEFORM_API_TOKEN ?? "",
  typeformWebhookSecret: process.env.TYPEFORM_WEBHOOK_SECRET ?? "",
  appUrl: process.env.APP_URL ?? "https://databitecoach.com",
  slackBotToken: process.env.SLACK_BOT_TOKEN ?? "",
  googleSheetsApiKey: process.env.GOOGLE_SHEETS_API_KEY ?? "",
  managerSlackId: process.env.MANAGER_SLACK_ID ?? "",
  port: parseInt(process.env.PORT ?? "3000", 10),
  googleClientId: process.env.GOOGLE_CLIENT_ID ?? "",
  googleClientSecret: process.env.GOOGLE_CLIENT_SECRET ?? "",
  telegramBotToken: process.env.TELEGRAM_BOT_TOKEN ?? "",
  telegramManagerChatId: process.env.TELEGRAM_MANAGER_CHAT_ID ?? "",
};
